server:
  port: 8189
  servlet:
    context-path: /fileTransfer
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
  servlet:
    multipart:
               max-file-size: 10MB
               max-request-size: 10MB
               enabled: true
               location: /files
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
